version: 2.1
description: Generate reports from phpunit-test wordpress

commands:
  init_env:
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt install -y git
      - checkout
      - run:
          name: Configuration
          command: |
            apt-get update -yqq
            apt install git libpq-dev libzip-dev zip -yqq
            apt-get -yqqf install vim wget zip unzip subversion default-mysql-client libmcrypt-dev default-libmysqlclient-dev php7.3-mysql --fix-missing
            apt-get install -y mysql-client
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install
            bash bin/install-wp-tests.sh wordpress wordpress wordpress "127.0.0.1" latest true
  run_phpcs:
    steps:
      - run:
          name: WP Coding standard check
          command: composer run phpcs
  run_phpunit:
    steps:
      - run:
          name: Run WP Phpunit
          command: composer run test

executors:
  php_mysql_executor:
    docker:
      - image: phpdockerio/php73-fpm
      - image: mysql:5.7.27
        environment:
          MYSQL_ROOT_PASSWORD: somewordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress

jobs:
  phpcs:
    steps:
      - run_phpcs
  phpunit:
    executor: php_mysql_executor
    steps:
      - init_env
      - run_phpunit


# Orchestrate our job run sequence
workflows:
  version: 2
  phpcs_unit_test:
    jobs:
      - phpcs
      - phpunit:
          requires:
            - phpcs